---
language: python
cache: pip

env:
  matrix:
    - MOLECULE_DISTRO: debian10

# Install python-pip
addons:
  apt:
    packages:
      - python-pip

install:
  # Install test dependencies
  - pip install molecule[docker,lint]

  # Print versions
  - molecule --version

script:
  - molecule test -s docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
